name: apebites_mex
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0

  # add flutter_bloc for state management
  flutter_bloc: ^8.0.0

  # add Lexend fonts
  google_fonts:  ^4.0.3

  # sliding navigation bar
  custom_sliding_segmented_control: ^1.7.4

  # add url launcher to open links
  url_launcher: ^6.0.3

  # add carousel slider
  carousel_slider: ^4.2.1

  # add colorful safe area
  colorful_safe_area: ^1.0.0

  # add go_router
  go_router: ^7.0.2

  # add heroicons
  heroicons: ^0.8.0
  auto_size_text: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: Lexend
      fonts:
        - asset: fonts/Lexend-Thin.ttf
          weight: 100
        - asset: fonts/Lexend-ExtraLight.ttf
          weight: 200
        - asset: fonts/Lexend-Light.ttf
          weight: 300  
        - asset: fonts/Lexend-Regular.ttf
          weight: 400
        - asset: fonts/Lexend-Medium.ttf
          weight: 500
        - asset: fonts/Lexend-Bold.ttf
          weight: 700
        - asset: fonts/Lexend-ExtraBold.ttf
          weight: 800
        - asset: fonts/Lexend-Black.ttf
          weight: 900
  uses-material-design: true
  assets:
    - assets/images/